### PR TITLE
Simple test fails

### PR DESCRIPTION
**Pull request by richelbilderbeek**
Both sfml-tmxloader and [STP](https://github.com/edoren/STP) do not work anymore on a standard Tiled map. I suspect something upstream changed, but I have no clue.

To help you find the problem, I have created a test case. It loads a standard tiled map and checks that the number of layers is non-zero. It fails on that assert. 

The test can be run with:

```
cd tests
./test.sh
```

I am willing to volunteer to find this bug, but I do need a little push in the back. OTOH, it may be trivially easy for you to find.

I also submitted the same test to [STP](https://github.com/edoren/STP), that suffers the same problem, as a Pull Request, so I assume if one fixes the bug, it will be easier for the other to follow.

### CODE REVIEW

**Comment by fallahn** [comment]
Thanks for the heads up, I had not yet come across this. Unfortunately I do not have the time right now to work on it right away, so if you want to volunteer yourself it would be highly appreciated (not just by me but by everyone who uses this lib)!

**Comment by fallahn** [comment]
I would say, however, that rather than merge these tests with the master branch that perhaps it would be wiser to work on a new branch specifically until the problem is found.

**Comment by richelbilderbeek** [comment]
Thanks for the friendly response. I will post an Issue and let people fork my repo. Then this PR will update with good code. Sounds like a plan?

**Comment by fallahn** [comment]
Sounds good to me.

**Pull request closed without merging**
